package nfm.open;

public class UTF8Junk {

    final static String[][] messages = {
            GameSparker.cut("I dream of becoming a carrot. When I'm home alone I dig holes in the backyard and stand in them, put lettuce on top of my head from sun up to sun down. I would steal sun tan spray from stores and use it until I turned a bright orange. People tell me it's impossible for me to be a carrot but I know I can be anything I want to be"),

            GameSparker.cut("🆗 son, 🌞 there ain't❌❌a ☝single☝fucking☝person☝ with any intellect👓👓📖who gives a 🎮remote🎮fuck🎮about your extensive vaping💯😎💨 talent. 😂I happen to be quite🎩the🎩intellectual🎩myself, so I can confirm✔✔this fact💯as truth™.👌if👌you👌think👌 that your vape💯😎💨 is going↗to get you hoes👯👯, you are utterly🐄 mistaken❌, fam👪."),
            GameSparker.cut("All you fuccbois 😽 😽 out there❓❓ Tryna talk shit 💩 against me?? 🗡🗡 🗡 Oh... I see 👀 👀 you have a gun 🔫. Do ✅ you? You have a gun 🔫 🔫, do you ✅ ✅⁉️ I'll put ⬇️ down ⬇️ my weapon 🗡 🚮 … I'll put ⬆️ down ⬇️ my weapon 🗡🚫... I 👀 will put down ⬇️ my WEAPON ‼️⚔⚔ AHAAA ‼️ I GOT ANOTHER 🗡 FUCKIN 🗡 SWORD ⚔⚔ YOU FUCKIN BITCH‼️👀 👀 ✅ 😎﻿"),
            GameSparker.cut("You know what I don't understand? No one ever takes memes seriously. I'm being honest here. No one ever stops and really understands the memes. They just pass it off as just another shitpost that was made by some edgy shit in his basement. These people are wrong. They aren't trash. They are art. "),
            GameSparker.cut("Life is like a cabbage: Sometimes it is green and crunchy, sometimes dad stabs the cat with a knife because his foot ball team lose again"),
            GameSparker.cut("Excuse me? I find vaping to be one of the best things in my life. It has carried me through the toughest of times and brought light and vapor upon my spirit. You're just another one of those people who doesn't believe in chem trails and fluoride turning us gay. Have fun being a slave to todays's system.﻿"),
            GameSparker.cut("ヽ༼ຈل͜ຈ༽ﾉ ʀᴀɪsᴇ ᴜʀ ᴅᴏɴɢᴇʀs ヽ༼ຈل͜ຈ༽ﾉ"),
            GameSparker.cut("DO IT, just DO IT! Don’t let your dreams be dreams. Yesterday, you said tomorrow. So just. DO IT! Make. your dreams. COME TRUE! Just… do it! Some people dream of success, while you’re gonna wake up and work HARD at it! NOTHING IS IMPOSSIBLE!"),
            GameSparker.cut("What the fuck did you just fucking say about me, you little bitch? I’ll have you know I graduated top of my class in the Navy Seals, and I’ve been involved in numerous secret raids on Al-Quaeda, and I have over 300 confirmed kills. I am trained in gorilla warfare and I’m the top sniper in the entire US armed forces. You are nothing to me but just another target. I will wipe you the fuck out with precision the likes of which has never been seen before on this Earth, mark my fucking words. You think you can get away with saying that shit to me over the Internet? Think again, fucker. As we speak I am contacting my secret network of spies across the USA and your IP is being traced right now so you better prepare for the storm, maggot. The storm that wipes out the pathetic little thing you call your life. You’re fucking dead, kid. I can be anywhere, anytime, and I can kill you in over seven hundred ways, and that’s just with my bare hands. Not only am I extensively trained in unarmed combat, but I have access to the entire arsenal of the United States Marine Corps and I will use it to its full extent to wipe your miserable ass off the face of the continent, you little shit. If only you could have known what unholy retribution your little “clever” comment was about to bring down upon you, maybe you would have held your fucking tongue. But you couldn’t, you didn’t, and now you’re paying the price, you goddamn idiot. I will shit fury all over you and you will drown in it. You’re fucking dead, kiddo."),
            GameSparker.cut("helo my name is dongerino pasterino ヽ༼ຈل͜ຈ༽ﾉ, i am 69 year old donger from imaqtmeatloaf’s stream . 420 years ago i was kidnapped and put into a donger concentration camp for 9001 years. 1 year ago, imaqtlasagne and imaqtpie invaded the camp and rescued me. now i work as teacherino, passing down the wisdom of ( ͡° ͜ʖ ͡°) to young dongers."),
            GameSparker.cut("Gr8 b8, m8. I rel8, str8 appreci8, and congratul8. I r8 this b8 an 8/8. Plz no h8, I’m str8 ir8. Cre8 more, can’t w8. We should convers8, I won’t ber8, my number is 8888888, ask for N8. No calls l8 or out of st8. If on a d8, ask K8 to loc8. Even with a full pl8, I always have time to communic8 so don’t hesit8"),
            GameSparker.cut("˙ʇı ןןɐɔ noʎ ɹǝʌǝʇɐɥʍ ɹo ,ɐʇǝq, pǝɹǝpısuoɔ buıǝq ɟo ʞɔıs ɯ,ı ˙ʇı ʇnoqɐ ʎɹɔ oʇ ǝɯ oʇ ʞןɐʇ ʎןuo puɐ ‘ʇıɥs ǝʞıן ɯǝɥʇ ʇɐǝɹʇ oɥʍ sʎnb bɐqǝɥɔnop ɹǝʇɟɐ ob sʎɐʍןɐ sןɹıb ǝsǝɥʇ puǝ ǝɥʇ uı ˙ʎpɐן,ɯ ɹoɟ buıɥʇʎuɐ op pןnoʍ puɐ ‘qoظ ǝɔıu ɐ ʞɹoʍ ‘ʎnb ǝɔıu ɐ ɯ,ı ˙ǝuoz puǝıɹɟ ǝɥʇ uı ʇnd buıǝq sʎɐʍןɐ ı ɯɐ ʎɥʍ"),
            GameSparker.cut("That’s it, I’m done. Fuck this chat. It’s devolved into a mass of retarded copy pastes and face spam. The quality of twitch chat has been declining for a while, but this is the last straw. That’s it. I’m done. I’m uninstalling the internet, chopping off my dick and moving to fucking Antarctica, at least the bacteria there will be fucking smarter discourse"),
            GameSparker.cut("ʜᴇʟʟᴏ ᴄʜᴀᴛ ɪ ᴀᴍ ғᴀᴍᴏᴜs ғᴀsᴄɪsᴛ ʟᴇᴀᴅᴇʀ, ᴀᴅᴏʟғ ʜɪᴛʟᴇʀɪɴᴏ. ᴡᴇ ᴡᴏᴜʟᴅ ʟɪᴋᴇ ʏᴏᴜ ᴀɴᴅ ɴᴀᴢɪ ᴍᴏᴅs ᴛᴏ ᴘᴀʀᴛɪᴄɪᴘᴀᴛᴇ ɪɴ ᴏᴜʀ ɴᴇᴡ ᴘʀᴏᴘᴀɢᴀɴᴅᴀ ғɪʟᴍ “sɪᴇɢ ʜᴇɪʟ ʟɪғᴇsᴛʏʟᴇ” ʏᴏᴜ ᴡᴏᴜʟᴅ ʀᴀɪsᴇ ʏᴏᴜʀ ᴅᴏɴɢᴇʀs ᴀɴᴅ ɴᴀᴢɪ ᴍᴏᴅs sᴀʏ ɴᴏ ᴘᴀsᴛᴇʀɪɴᴏ ᴀɴᴅ ʙᴀɴʜᴀᴍᴍᴇʀ."),
            GameSparker.cut("Has anyone really been far even as decided to use even go want to do look more like?"),
    };
}
